from . import bbc
from . import cnn
from . import eldiario
from . import elpais
from . import financialtimes
from . import infolibre
from . import lavanguardia
from . import lemonde
from . import nytimes
from . import thetimes
from . import wallstreetjournal
